services:
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    image: nginx:debian
    depends_on :
      - wordpress
    networks:
      - inception
    ports:
      - "127.0.0.1:443:443"
    volumes:
      - wordpress_data:/var/www/html/wordpress
    restart: always

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    image: mariadb:debian
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    env_file:
      - .env
    restart: always

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    image: wordpress:debian
    depends_on: 
      - mariadb
    volumes:
      - wordpress_data:/var/www/html/wordpress
    networks:
      - inception
    env_file:
      - .env
    restart: always

networks:
  inception:

volumes:
  mariadb_data: 
    driver: local
    driver_opts:
      device: /home/$USER/data/mysql
      type: volume
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      device: /home/$USER/data/wordpress
      type: volume
      o: bind