global:
  scrape_interval: 15s
  external_labels:
    monitor: 'nginx'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'nginx'
    scrape_interval: 5s
    static_configs:
      - targets: ['nginx:9913']