#!/bin/bash
####################################
#
# Backup script
#
####################################

# What to backup. 
backup_files="/var/lib/redis/dump.rdb"

# Where to backup to.
dest="/etc/redis/"

# Create archive filename.
day=$(date +%A)
hostname=$(hostname -s)
archive_file="$hostname-$day.redis-backup.tgz"

# Print start status message.
echo "Backing up $backup_files to $dest/$archive_file"
date
echo

# Backup the files using tar.
tar czf $dest/$archive_file $backup_files
chmod 777 $dest/$archive_file

# Print end status message.
echo
echo "Backup finished"
date

# Long listing of files in $dest to check file sizes.
ls -lh $dest
